controller_list:
  - name: fake_main_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base_to_arm1
      - arm1_to_sphere1
      - sphere1_to_arm2
      - arm2_to_sphere2
      - sphere2_to_arm3
      - arm3_to_prismatic
initial:  # Define initial robot poses per group
  - group: main_planning_group
    pose: home